name: Build packages

on:
  push:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - panel
          - panel-nightly
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: calagopus-nix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build ${{ matrix.package }}
        run: nix build .#${{ matrix.package }}
